version: '3'

services:
  web:
    build: .
    command: /entrypoint.sh
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=TodoMaster.settings
      - PYTHONUNBUFFERED=1
    restart: always

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=tododb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    restart: always

volumes:
  postgres_data:
  static_volume:
